name: Deploy (Shinylive)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Build wheel for lzstring
        run: |
          pip wheel --wheel-dir wheels lzstring==1.0.4

      - name: Export with Shinylive
        run: |
          pip wheel --wheel-dir ./pyodide-packages lzstring==1.0.4
          shinylive export . ./site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
