name: Deploy (Shinylive)

on:
  push:
    branches: [main]

permissions:              # top-level = applies to all jobs
  contents: read
  pages: write             # allow publish
  id-token: write          # OIDC for Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:           # ✅ REQUIRED
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt       # dev tools (ruff)

      - name: Export with Shinylive
        run: shinylive export . site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
